### Package Imports

In [2]:
import numpy as np

# Assignment 1: Array Basics

Hi there,

Can you import Numpy and convert the following list comprehension (I just learned about comprehensions in an awesome course by Maven) into an array?

Once you've done that report the following about the array:
* The number of dimensions 
* The shape
* The number of elements in the array
* The type of data contained inside

In [2]:
my_list = [x * 10 for x in range(1, 11)]

In [3]:
my_list_array=np.array(my_list)

In [4]:
my_list_array

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [14]:
print('number of diamentions= {}'.format(my_list_array.ndim))
print('the shape= {}'.format(my_list_array.shape))
print('number of elements= {}'.format(my_list_array.size))
print('type of data= {}'.format(my_list_array.dtype))

number of diamentions= 1
the shape= (10,)
number of elements= 10
type of data= int32


# Assignment 2: Array Creation

Thanks for your help with the first piece - I'm starting to understand some of the key differences between base Python data types and NumPy arrays. 

Does NumPy have anything like the range() function from base Python?

If so: 
* create the same array from assignment 1 using a NumPy function. 
* Make it 5 rows and 2 columns. 
* It's ok if the datatype is float or int.

In [28]:
my_array=np.arange(10,101,10)
reshape=np.arange(10,101,10).reshape(5,2)
print('my_array = ',my_array)
reshape

my_array =  [ 10  20  30  40  50  60  70  80  90 100]


array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

Looking good so far! One of our data scientists asked about random number generation in NumPy.

Can you create a 3x3 array of random numbers between 0 and 1? Use a random state of 2022.

Store the random array in a variable called `random_array`.

In [36]:
rng=np.random.default_rng(1)
random_array=rng.random(9)
random_array2D=random_array.reshape(3,3)
random_array2D

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645],
       [0.82770259, 0.40919914, 0.54959369]])

# Assignment 3: Accessing Array Data


Slice and index the `random_array` we created in the previous exercise. Perform the following:

* Grab the first two 'rows' of the array
* Grab the entire first column
* Finally, grab the second selement of the third row.

Thanks!


In [37]:
random_array2D

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645],
       [0.82770259, 0.40919914, 0.54959369]])

In [39]:
random_array2D[0:2,:]

array([[0.51182162, 0.9504637 , 0.14415961],
       [0.94864945, 0.31183145, 0.42332645]])

In [43]:
random_array2D[:,:1]

array([[0.51182162],
       [0.94864945],
       [0.82770259]])

In [44]:
random_array2D[2,1]

0.4091991363691613

In [45]:
random_array2D[:,0]

array([0.51182162, 0.94864945, 0.82770259])

# Assignment 4: Arithmetic Operations

The creativity of our marketing team knows no bounds!

They've asked us to come up with a simple algorithm to provide a random discount to our list of prices below. 

Before we do that, 

* Add a 5 dollar shipping fee to each price. Call this array `total`.

Once we have that, we want to use the random_array created in assignment 2 and apply them to the 6 prices.

* Grab the first 6 numbers from `random_array`, reshape it to one dimension. Call this `discount_pct`.
* Subtract `discount_pct` FROM 1, store this in `pct_owed`.
* Multiply `pct_owed` by `total` to get the final amount owed.

In [48]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])
total=prices+5
total

array([ 10.99,  11.99,  27.49, 104.99,   9.99,  54.99])

In [60]:
random_array=random_array2D[0:2,:]

In [63]:
discount_pct=random_array.reshape(1,6)
discount_pct

array([[0.51182162, 0.9504637 , 0.14415961, 0.94864945, 0.31183145,
        0.42332645]])

In [66]:
pct_owned=1-discount_pct
pct_owned

array([[0.48817838, 0.0495363 , 0.85584039, 0.05135055, 0.68816855,
        0.57667355]])

In [69]:
final=pct_owned*total
final

array([[ 5.36508034,  0.59394028, 23.52705225,  5.39129455,  6.87480379,
        31.71127857]])

# Assignment 5: Filtering Arrays

Filter the product array to only include those with prices greater than 25.

Modify your logic to include cola, despite it not having a price greater than 25. 
Store the elements returned in an array called `fancy_feast_special`.

Next, create a shipping cost array where the cost is 0 if price is greater than 20, and 5 if not. 

In [9]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])
products = np.array(["salad", "bread", "mustard", "rare tomato", "cola", "gourmet ice cream"])

fancy_feast_special=products[ (prices>25 )| (products == 'cola')]
fancy_feast_special

array(['rare tomato', 'cola', 'gourmet ice cream'], dtype='<U17')

In [17]:
shipping_cost=np.where(prices>20,0,5) 
shipping_cost

array([5, 5, 0, 0, 5, 0])

# Assignment 6: Aggregating and Sorting Arrays

First, grab the top 3 highest priced items in our list. 

Then, calculated the mean, min, max, and median of the top three prices.

Finally, calculate the number of unique price tiers in our `price_tiers` array.

In [23]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])

prices.sort()
prices

array([ 4.99,  5.99,  6.99, 22.49, 49.99, 99.99])

In [29]:
prices_top3=prices[:2:-1]
prices_top3

array([99.99, 49.99, 22.49])

In [36]:
print('mean=',prices_top3.mean())
print('min=',prices_top3.min())
print('max=',prices_top3.max())
print('median=',np.median(prices_top3))

mean= 57.49
min= 22.49
max= 99.99
median= 49.99


In [38]:
price_tiers = np.array(["budget", "budget", "mid-tier", "luxury", "mid-tier", "luxury"])

In [47]:
np.unique(price_tiers)

array(['budget', 'luxury', 'mid-tier'], dtype='<U8')

# Assignment 7: Bringing it All Together

Ok, final NumPy task - let's read in some data with the help of Pandas.

Our data scientist provided the code to read in a csv as a Pandas dataframe, and has converted the two columns of interest to arrays.

* Filter `sales_array` down to only sales where the product family was produce. 

* Then, randomly sample roughly half (random number < .5) of the produce sales and report the mean and median sales. Use a random seed of 2022.

* Finally, create a new array that has the values 'above_both', 'above_median', and 'below_both' based on whether the sales were above the median and mean of the sample, just above the median of the sample, or below both the median and mean of the sample. 

In [64]:
import pandas as pd
import numpy as np

retail_df = pd.read_csv(
    "../retail/retail_2016_2017.csv", skiprows=range(1, 11000), nrows=1000
)

family_array = np.array(retail_df["family"])
sales_array = np.array(retail_df["sales"])


In [65]:
produce_array=sales_array[family_array == 'PRODUCE']
produce_array

array([1662.394,  447.064, 2423.944,  962.866, 1236.404,  298.441,
       1077.44 , 3404.531,  962.96 ,  279.505, 1852.786, 1089.319,
        726.516, 7860.031,  446.038, 1155.385,  120.202,  862.092,
        473.952,  254.263, 1272.755, 2775.771, 2030.762, 1657.432,
       2339.906,  722.333, 1567.843, 2458.456,  673.885, 8834.15 ])

In [66]:
rng=np.random.default_rng(2022)
random_array=rng.random(30)
random_array

array([0.24742606, 0.09299006, 0.61176337, 0.06066207, 0.66103343,
       0.75515778, 0.1108689 , 0.04305584, 0.41441747, 0.98862926,
       0.96919869, 0.25697153, 0.55876211, 0.24234798, 0.32202029,
       0.89135975, 0.94611366, 0.72253931, 0.92847437, 0.99608701,
       0.2494223 , 0.06229007, 0.94479027, 0.65028587, 0.32167568,
       0.08336384, 0.21924361, 0.08417791, 0.05213927, 0.20525022])

In [69]:
sampled_array=produce_array[random_array<0.5]

In [71]:
mean = sampled_array.mean()
mean

2268.102470588235

In [74]:
median=np.median(sampled_array)
median

1272.755

In [82]:
final_array=np.where(sampled_array<median,'below both',np.where(sampled_array>mean,'above both','above median'))
final_array

array(['above median', 'below both', 'below both', 'below both',
       'above both', 'below both', 'below both', 'above both',
       'below both', 'above median', 'above both', 'above both',
       'below both', 'above median', 'above both', 'below both',
       'above both'], dtype='<U12')

In [88]:
sampled_array

array([1662.394,  447.064,  962.866, 1077.44 , 3404.531,  962.96 ,
       1089.319, 7860.031,  446.038, 1272.755, 2775.771, 2339.906,
        722.333, 1567.843, 2458.456,  673.885, 8834.15 ])